openapi: 3.0.3
info:
  title: SkyJoy Auth API
  version: 1.0.0
  description: Authentication APIs for SkyJoy Partner Realm

servers:
  - url: https://id.uat.skyjoy.io/realms/loyalty-partner

paths:
  # Include separate API files
  <<: 
    $ref: './paths/token-password.yaml'
  <<:
    $ref: './paths/token-refresh.yaml'