# main.yaml
openapi: 3.0.3
info:
  title: SkyJoy Auth API
  version: 1.0.0
  description: Authentication API for SkyJoy partner

servers:
  - url: https://id.uat.skyjoy.io/realms/loyalty-partner

paths:
  $ref: ./paths/login.yaml