openapi: 3.0.3
info:
  title: SkyJoy Auth API
  version: 1.0.0
  description: Authentication API for SkyJoy partner
servers:
  - url: 'https://id.uat.skyjoy.io/realms/loyalty-partner'
paths:
  /protocol/openid-connect/token:
    post:
      summary: Token Endpoint (password / refresh_token grant)
      description: |
        Unified token endpoint supporting:
          - `grant_type=password`: for Resource Owner Password Credentials flow
          - `grant_type=refresh_token`: to refresh access token
      operationId: issueToken
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              oneOf:
                - title: Password Grant Request
                  type: object
                  required:
                    - grant_type
                    - username
                    - password
                    - client_id
                    - client_secret
                  properties:
                    grant_type:
                      type: string
                      enum:
                        - password
                      description: OAuth2 grant type
                      example: password
                    username:
                      type: string
                      description: End user's username
                      example: demo_user@partner.com
                    password:
                      type: string
                      description: End user's password
                      example: P@ssw0rd!
                    client_id:
                      type: string
                      description: Client ID
                      example: loyalty-partner-client
                    client_secret:
                      type: string
                      description: Client secret
                      example: abcd1234efgh5678ijkl90mnop
                - title: Refresh Token Grant Request
                  type: object
                  required:
                    - grant_type
                    - refresh_token
                    - client_id
                    - client_secret
                  properties:
                    grant_type:
                      type: string
                      enum:
                        - refresh_token
                      description: OAuth2 grant type
                      example: refresh_token
                    refresh_token:
                      type: string
                      description: Refresh token issued from previous login
                      example: eyJh...Q
                    client_id:
                      type: string
                      description: Client ID
                      example: loyalty-partner-client
                    client_secret:
                      type: string
                      description: Client secret
                      example: abcd1234efgh5678ijkl90mnop
      responses:
        '200':
          description: Token response
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: JWT bearer access token
                    example: eyJhbGciOiJIUzI1NiIs...
                  refresh_token:
                    type: string
                    description: Refresh token
                    example: eyJhbGciOiJIUzI1NiIs...
                  expires_in:
                    type: integer
                    description: Expiration time (seconds)
                    example: 300
                  token_type:
                    type: string
                    example: bearer
                  scope:
                    type: string
                    example: openid profile email
        '400':
          description: Invalid request
        '401':
          description: Unauthorized - Invalid credentials
      tags:
        - Authentication
